### ISSUE TITLE
Bad example for 'break' and 'continue'

### ISSUE THREAD

**Issue by Plato-D** [java1cprog/simple-about-rust#3]
Добрый день! 

Ваш пример ниже:

```rust
fn main() {
    let mut j = 0;
    while j <= 256 {
        j += 1;
        if j % 2 == 0 {
            continue;
        }
        print!("{} ", j * j);
    }
}

```
для ключевого слова `continue` неудачный, поскольку не демонстрирует его работу. 
В результате работы программы последним выводится число `39601 = 199 * 199`.
Для получения такого результата доп. инструкция `else if` со словом `continue` является излишней, равно как и ключевое слово `break`, т.к. достаточно прописать `while j < 200` и результат будет тот же.

Чтобы продемонстрировать, как работает `continue`, можно использовать такой пример:

```rust
fn main() {
    let mut j = 0;
    while j <= 256 {
        j += 1;
        if j % 2 == 0 {
            continue;
        }
        print!("{} ", j * j);
    }
}

```
Программа возводит в квадрат только нечетные числа (до `256`).

А вот пример, который демонстрирует, как работает `break`:
```rust
fn main() {
    let mut j = 0;
    while j < 256 {
        let k = j * j;
        j += 1;
        print!("{} ", k);
        if k >= 40000 {
            break;
        }
    }
}

```

Я пока что не программист, учусь на ваших примерах :-)

**Comment by rustkas** [comment]
#### Добрый день!

Внёс Ваши рекомендации в [текст](https://github.com/rustkas/simple-about-rust/blob/master/ch-05-controlling-execution-flow.md).

@Plato-D! Благодрю за Ваши конструктивные рекомендации.

**Comment by rustkas** [comment]
Все рекомендации реализованы в учебном пособии.
